name: Deploy Node.js App in AWS EC2

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: jovemhero/todo-api:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            docker stop todo-api || true
            docker rm todo-api || true
            docker image rm jovemhero/todo-api:latest || true
            docker pull jovemhero/todo-api:latest
            docker run -d --name todo-api \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e USER_EMAIL="${{ secrets.USER_EMAIL }}" \
              -e PASS_EMAIL="${{ secrets.PASS_EMAIL }}" \
              -e R2_ENDPOINT="${{ secrets.R2_ENDPOINT }}" \
              -e R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}" \
              -e R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}" \
              -e R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}" \
              -e REDIS_HOST="${{ secrets.REDIS_HOST }}" \
              -e REDIS_PORT="${{ secrets.REDIS_PORT }}" \
              -e SECRET_ACCESS_JWT="${{ secrets.SECRET_ACCESS_JWT }}" \
              -e SECRET_REFRESH_JWT="${{ secrets.SECRET_REFRESH_JWT }}" \
              -p 3000:3000 jovemhero/todo-api:latest
